name: run tests on any Push event
on: push

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: action/checkout@v3
      - name: Install Python
        uses: action/setup-python@v4
        with:
          python-version: '3.7'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: python -m pytest
